### ISSUE TITLE
DCN.prmtop missing

### ISSUE THREAD

**Issue by ghost** [igemsoftware/Heidelberg_15#3]
MAWS.py ./ IL6_edited.pdb
['DGN', 'DAN', 'DTN', 'DCN']
Choosing from candidates ...
Constructing Ligand/Aptamer complex ...
Constructing Ligand/Aptamer complex ...
Constructing Ligand/Aptamer complex ...
Constructing Ligand/Aptamer complex ...
Aptamer/Ligand complex constructed.
Loading Aptamer/Ligand complex ...
Aptamer/Ligand complex constructed.
Loading Aptamer/Ligand complex ...
Aptamer/Ligand complex constructed.
Loading Aptamer/Ligand complex ...
Traceback (most recent call last):
  File "/home/theoa/qiime-env/env/bin/MAWS.py", line 1212, in <module>
Aptamer/Ligand complex constructed.
Loading Aptamer/Ligand complex ...
    positions_and_Ntides = loop()
  File "/home/theoa/qiime-env/env/bin/MAWS.py", line 1105, in loop
    pos_Nt_S_task = pool.map(initial,alphabet)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
IOError: [Errno 2] No such file or directory: 'DCN.prmtop'

**Comment by ghost** [comment]
After changing 1106 and 1107 to remove Pool use and trying one 'alphabet' at a time I get the same error as previously reported :KeyError: 
return float(self._raw_data['POINTERS'][index])
KeyError: 'POINTERS'

**Comment by zachmueller** [comment]
@bioinformatics-deakin did you ever figure out how to resolve this? I'm running into a similar issue trying to get the code to work. I'm unfamiliar with where the DCN.prmtop file even comes from--do you have a clue where we are supposed to get that? Or does the file get created on the fly while processing the .pdb file?

**Comment by ghost** [comment]
Hi,

the file is an Amber Tools File. I never got MAWS to work and I think as it is, it never will. I contacted the developers but I got no reply.

Sorry can't be more help.

Theo




________________________________________

**Comment by Abhigna18** [comment]
Hii 
did anyone resolve this even I am getting the same error.
please help
Thank you
